### ISSUE TITLE
Several questions about your code

### ISSUE THREAD

**Issue by Waterman178** [btbd/smap#11]
`VOID Translator::TraceBranch(INT &translationIndex, INT startingIndex) {
	auto rva = this->Translations[translationIndex].get()->RVA();

	auto branch = this->Branches.find(rva.Start());
	if (branch != this->Branches.end()) {
		auto xref = branch->second;
		if (xref < rva.Start()) {
			for (; translationIndex >= startingIndex; --translationIndex) {
				if (this->Translations[translationIndex].get()->RVA().Start() == xref) {
					break;
				}
			}//#1

			while (translationIndex - 1 >= startingIndex && this->Translations[static_cast<SIZE_T>(translationIndex) - 1].get()->RVA().Start() == xref) {
				--translationIndex;
			}//#2
		}
	}
}`

# 1 and # 2 have the same function.I don't understand why?

`auto prevRelative = dynamic_cast<RelativeTranslation *>(prevTrans);
			//#3
			if (prevRelative && prevRelative->Pointer() == nullptr && Util::IsSameRegister(op0.reg.value, offset.Register)) {
				continue;
			}
`
What does the code at # 3 mean?(if (prevRelative && prevRelative->Pointer() == nullptr && Util::IsSameRegister(op0.reg.value, offset.Register)) )

It would be nice if your project  was commented.Also, how compatible is it?I want to spread the instructions of the driver(64 bit)

**Comment by btbd** [comment]
@Waterman178 Multiple translations can have the same RVA if the original instruction is being replaced with multiple. So, we must walk backwards and find the first translation that has the RVA (which is what 2 does) after finding the last instance (which is what 1 does).

The code at 3 seeks out relative instructions that use the same destination register as `op0` and use the RVA 0, so it looks for instructions like `lea rax, cs:0` if `rax` is `op0`.

You are right that I should document the code more, but I lack motivation as I personally don't use this project. You can definitely convert it to map a driver. The main issue with compatibility is dealing with all the different compilers (*cough* jump tables) because it must do perfect static analysis for the tool to function properly.
