### ISSUE TITLE
我并不是很理解  这个可以躲避CRC检测吗？ 我在函数头看到了 JMP

### ISSUE THREAD

**Issue by jmp19940829** [btbd/smap#23]

**Comment by btbd** [comment]
@jmp19940829 This doesn't avoid CRC detection. If you specify a function as an export then it would fail integrity checks given the section it scatters it to was not writeable according to the section header.

This project was initially written to abuse internal heuristics used by anti-cheats, which more-or-less included things like:
1. Checking for non-image executable memory more than the size of a page.
2. Allowing hooks on functions given following the JMPs lead to an image backed address.
3. Since they allow some hooks in some modules, they would either do no integrity checks on some modules, do integrity checks on specific sections of specific modules, do integrity checks on commonly targeted functions, or do full integrity checks and report differences.

The main reason these heuristics are in place is that legitimate software places inline hooks and allocates executable memory outside of a module for trampolines. Regardless, this project is quite easy to detect so I wouldn't count on it nowadays.
